// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// // Register each controller with Stimulus
import SelectController from "./select_controller"
application.register("select", SelectController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TurboController from "./turbo_controller"
application.register("turbo", TurboController)